export default Object.freeze({
    LISTING_DETAILS: "ListingDetails",
    LISTING_EDIT: "ListingEdit",
    LOGIN: "Login",
    MESSAGES: "Messages",
    REGISTER: "Register",
    REGISTER_SUCCESS: "RegisterSuccess",
    FORGOT_PASSWORD: 'ForgotPassword',
    RESET_PASSWORD: 'resetpassword',
    CHAT: 'chat',
    USERSMODAL: 'usersModal',
    FEEDBUTTONS: 'Feedbuttons',
    FORSALE: 'ForSale',
    LOSTFOUND: 'LostFound',
    CAMPUS_EVENTS: 'CampusEvents',
    ROOMMATE: 'Roommate',
  });